import { FormEvent, useEffect, useState } from 'react'
import { approveInventoryAddition, createInventoryAdditionRequest, getInventoryAdditionRequests, rejectInventoryAddition, Role } from './api'

type Props = { role: Role; onToast: (message: string) => void }

export default function InventoryRequestsPanel({ role, onToast }: Props) {
  const [requests, setRequests] = useState<Awaited<ReturnType<typeof getInventoryAdditionRequests>>['requests']>([])
  const [form, setForm] = useState({ product_name: '', quantity: '', batch_number: '', manufacturing_date: '', expiry_date: '' })
  const load = async () => { try { setRequests((await getInventoryAdditionRequests()).requests) } catch (error) { onToast(error instanceof Error ? error.message : 'Could not load inventory requests') } }
  useEffect(() => { void load() }, [])
  async function submit(event: FormEvent) { event.preventDefault(); const quantity = Number(form.quantity); if (!form.product_name.trim() || !Number.isFinite(quantity) || quantity < 1 || !form.batch_number.trim() || !form.manufacturing_date || !form.expiry_date) { onToast('Enter a valid product, quantity, batch, and dates'); return } try { await createInventoryAdditionRequest({ product_name: form.product_name.trim(), quantity, batch_number: form.batch_number.trim(), manufacturing_date: form.manufacturing_date, expiry_date: form.expiry_date }); onToast('Inventory request sent to manager'); setForm({ product_name: '', quantity: '', batch_number: '', manufacturing_date: '', expiry_date: '' }); await load() } catch (error) { onToast(error instanceof Error ? error.message : 'Could not submit inventory request') } }
  async function review(id: number, approve: boolean) { try { if (approve) await approveInventoryAddition(id); else await rejectInventoryAddition(id); onToast(approve ? 'Inventory request approved' : 'Inventory request rejected'); await load() } catch (error) { onToast(error instanceof Error ? error.message : 'Could not review inventory request') } }
  return <>{role === 'warehouse_worker' && <section className="panel workflow-card"><p className="eyebrow">Manager approval</p><h2>Request inventory addition</h2><form className="stack-form" onSubmit={submit}><label>Product name<input required placeholder="Enter any product" value={form.product_name} onChange={(event) => setForm({ ...form, product_name: event.target.value })} /></label><label>Quantity<input required type="number" min="1" placeholder="Enter quantity" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} /></label><label>Batch number<input required value={form.batch_number} onChange={(event) => setForm({ ...form, batch_number: event.target.value })} /></label><label>Manufacturing date<input required type="date" value={form.manufacturing_date} onChange={(event) => setForm({ ...form, manufacturing_date: event.target.value })} /></label><label>Expiry date<input required type="date" value={form.expiry_date} onChange={(event) => setForm({ ...form, expiry_date: event.target.value })} /></label><button className="button primary" type="submit">Send manager request</button></form></section>}{role === 'manager' && <section className="panel data-panel"><div className="table-toolbar"><div><p className="eyebrow">Inventory approvals</p><h2>{requests.filter((item) => item.status === 'pending').length} pending requests</h2></div><button className="button subtle" onClick={() => void load()}>Refresh</button></div>{requests.filter((item) => item.status === 'pending').map((item) => <div className="data-row compact" key={item.request_id}><strong>Request #{item.request_id}</strong><span>{item.product_name}</span><span>{item.quantity} units</span><button className="row-action" onClick={() => void review(item.request_id, true)}>Approve</button><button className="row-action danger" onClick={() => void review(item.request_id, false)}>Reject</button></div>)}</section>}</>
}
